#!/bin/bash
./Analytext.sh .title
cp WordFreq.dat .title.dat

./Analytext.sh .abstract
cp WordFreq.dat .abstract.dat

awk ' /'"Introduction"'/ {flag=1;next} /'"AOTF Spectrophotometer"'/{flag=0} flag { print }' Implementation.tex > ".Introduction"
./Analytext.sh ".Introduction"
cp WordFreq.dat ".Introduction_AOTF Spectrophotometer.dat"
awk ' /'"AOTF Spectrophotometer"'/ {flag=1;next} /'"Implementation"'/{flag=0} flag { print }' Implementation.tex > ".AOTF Spectrophotometer"
./Analytext.sh ".AOTF Spectrophotometer"
cp WordFreq.dat ".AOTF Spectrophotometer_Implementation.dat"
awk ' /'"Implementation"'/ {flag=1;next} /'"Embedded Systems Layer"'/{flag=0} flag { print }' Implementation.tex > ".Implementation"
./Analytext.sh ".Implementation"
cp WordFreq.dat ".Implementation_Embedded Systems Layer.dat"
awk ' /'"Embedded Systems Layer"'/ {flag=1;next} /'"Interfacing with the ASPU"'/{flag=0} flag { print }' Implementation.tex > ".Embedded Systems Layer"
./Analytext.sh ".Embedded Systems Layer"
cp WordFreq.dat ".Embedded Systems Layer_Interfacing with the ASPU.dat"
awk ' /'"Interfacing with the ASPU"'/ {flag=1;next} /'"AOTF Control"'/{flag=0} flag { print }' Implementation.tex > ".Interfacing with the ASPU"
./Analytext.sh ".Interfacing with the ASPU"
cp WordFreq.dat ".Interfacing with the ASPU_AOTF Control.dat"
awk ' /'"AOTF Control"'/ {flag=1;next} /'"Communicating with the Server"'/{flag=0} flag { print }' Implementation.tex > ".AOTF Control"
./Analytext.sh ".AOTF Control"
cp WordFreq.dat ".AOTF Control_Communicating with the Server.dat"
awk ' /'"Communicating with the Server"'/ {flag=1;next} /'"Embedded System Control Flow Chart"'/{flag=0} flag { print }' Implementation.tex > ".Communicating with the Server"
./Analytext.sh ".Communicating with the Server"
cp WordFreq.dat ".Communicating with the Server_Embedded System Control Flow Chart.dat"
awk ' /'"Embedded System Control Flow Chart"'/ {flag=1;next} /'"Server Layer"'/{flag=0} flag { print }' Implementation.tex > ".Embedded System Control Flow Chart"
./Analytext.sh ".Embedded System Control Flow Chart"
cp WordFreq.dat ".Embedded System Control Flow Chart_Server Layer.dat"
awk ' /'"Server Layer"'/ {flag=1;next} /'"Serialport"'/{flag=0} flag { print }' Implementation.tex > ".Server Layer"
./Analytext.sh ".Server Layer"
cp WordFreq.dat ".Server Layer_Serialport.dat"
awk ' /'"Serialport"'/ {flag=1;next} /'"SocketIO"'/{flag=0} flag { print }' Implementation.tex > ".Serialport"
./Analytext.sh ".Serialport"
cp WordFreq.dat ".Serialport_SocketIO.dat"
awk ' /'"SocketIO"'/ {flag=1;next} /'"MongoDB"'/{flag=0} flag { print }' Implementation.tex > ".SocketIO"
./Analytext.sh ".SocketIO"
cp WordFreq.dat ".SocketIO_MongoDB.dat"
awk ' /'"MongoDB"'/ {flag=1;next} /'"Client Layer"'/{flag=0} flag { print }' Implementation.tex > ".MongoDB"
./Analytext.sh ".MongoDB"
cp WordFreq.dat ".MongoDB_Client Layer.dat"
awk ' /'"Client Layer"'/ {flag=1;next} /'"Spectra Plotting"'/{flag=0} flag { print }' Implementation.tex > ".Client Layer"
./Analytext.sh ".Client Layer"
cp WordFreq.dat ".Client Layer_Spectra Plotting.dat"
